let wavecolors = {
  native: ['#ED1E79', '#FF00FF'],
  corridos: ['#fbcb3b', '#F7931E'],
  banda: ['yellow', '#ff0'],
}

function rand(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min) + min); //The maximum is exclusive and the minimum is inclusive
}

let data = [
  // {
  //   id: 'corridos-01',
  //   genre: 'corridos',
  //   genresvg: corridossvg,
  //   wavecolor: wavecolors.corridos[0],
  //   progresscolor: wavecolors.corridos[1],
  //   top: 50,
  //   left: 250,
  //   epicX: 200,
  //   epicY: 354,
  //   rotate: 0,
  //   trackName: 'La Bamba',
  //   trackImg: '',
  //   trackMP3: 'songs/la-bamba.mp3',
  //   trackStr: `something`
  // },
  // {
  //   id: 'corridos-02',
  //   genre: 'corridos',
  //   genresvg: corridossvg,
  //   wavecolor: wavecolors.corridos[0],
  //   progresscolor: wavecolors.corridos[1],
  //   top: 210,
  //   left: 600,
  //   epicX: 900,
  //   epicY: 320,
  //   rotate: 0,
  //   trackName: 'Adelita',
  //   trackImg: '',
  //   trackMP3: 'songs/Adelita.mp3',
  //   trackStr: `In April, the first of the month<br />
  //             On Holy Thursday in the morning,<br />
  //             Villa went forth from Parral<br />
  //             To launch and speed up a campaign`
  // },
  {
    id: 'indigenous-01',
    genre: 'native',
    genresvg: nativesvg,
    wavecolor: wavecolors.native[0],
    progresscolor: wavecolors.native[1],
    top: '67%',
    left: '31%',    
    trackName: 'Fireworks Music',
    trackMP3: 'songs/fireworks-music.mp3',
    trackStr: 'Very early in the morning "about four o\'clock" the Christmas fiesta is announced to the village by the playing of the chirimia and drum. Here we see traditional instruments and customs applied to imported religious ceremonies.',
    'trackImg': 'indian-music-of-mexico.jpg',
    'trackArtist': 'Laura C. Bouton',
    'trackAlbum': 'Indian music of Mexico sound recording / recorded in Mexico by Laura Boulton',
    'trackURL': 'https://folkways-media.si.edu/liner_notes/folkways/FW08851.pdf',
    locations: 'Oaxaca',
    'influences': 'Catholicism',
    'instruments': 'Chirimia | Drum'
  },
  {
    id: 'indigenous-02',
    genre: 'native',
    genresvg: nativesvg,
    wavecolor: wavecolors.native[0],
    progresscolor: wavecolors.native[1],
    top: '51%',
    left: '62%',  
    trackName: 'Flying Pole Dance',
    trackMP3: 'songs/flying-pole-dance.mp3',
    trackStr: 'Dance called Los Voladores, the Fliers, of the Otomi people.  Fliers dress as birds, wearing tall feather headdresses, and represent the sacred birds which guarded the points of the compass. The music is furnished by an older man who plays a flute and a little drum simulaneously.',
    'trackImg': 'indian-music-of-mexico.jpg',
    'trackArtist': 'Laura C. Bouton',
    'trackAlbum': 'Indian music of Mexico sound recording / recorded in Mexico by Laura Boulton',
    'trackURL': 'https://folkways-media.si.edu/liner_notes/folkways/FW08851.pdf',
    locations: 'Puebla',
    'influences': '',
    'instruments': 'Flute | Drum | Rattle'
  },
  {
    id: 'indigenous-03',
    genre: 'native',
    genresvg: nativesvg,
    wavecolor: wavecolors.native[0],
    progresscolor: wavecolors.native[1],
    top: '5%',
    left: '45%',   
    trackName: 'Deer Dance',
    trackMP3: 'songs/deer-dance.mp3',
    trackStr: 'The principal dancer is the Deer, or el Venado. On his head he wears of carries a stuffed deer\'s head, decorated with ribbons and flowers. A cloth hangs down to the knees and is held by a belt which has attached to it  many deer hoofs. Anklets of dried butterfly cocoons full of pebbles produce a pleasant clicking sound while he dances. In each hand he carries a llarge gourd rattle. The dance pantomines the hunt ad death of the deer.',
    'trackImg': 'indian-music-of-mexico.jpg',
    'trackArtist': 'Laura C. Bouton',
    'trackAlbum': 'Indian music of Mexico sound recording / recorded in Mexico by Laura Boulton',
    'trackURL': 'https://folkways-media.si.edu/liner_notes/folkways/FW08851.pdf',
    locations: 'Tlaxcala',
    'influences': '',
    'instruments': 'Notched Stick | Rattles | Water Drum'
  },
  {
    id: 'indigenous-04',
    genre: 'native',
    genresvg: nativesvg,
    wavecolor: wavecolors.native[0],
    progresscolor: wavecolors.native[1],
    top: '18%',
    left: '64%',   
    trackName: 'Las Pascolas',
    trackMP3: 'songs/las-pascolas.mp3',
    trackStr: 'Each Pascola dancer has a rattle, a rectangualr wooden frame inside of which brass or bronze discs stand on rods and give a loud jingling sound when shaken. Beside the drummer there is a small fire where he can tune his drum by heating the membrane over the embers in the same way that African drummers tune their drums.',
    'trackImg': 'indian-music-of-mexico.jpg',
    'trackArtist': 'Laura C. Bouton',
    'trackAlbum': 'Indian music of Mexico sound recording / recorded in Mexico by Laura Boulton',
    'trackURL': 'https://folkways-media.si.edu/liner_notes/folkways/FW08851.pdf',
    locations: 'Tlaxcala',
    'influences': '',
    'instruments': 'Flute | Drum | Bells'
  },
  {
    id: 'indigenous-05',
    genre: 'native',
    genresvg: nativesvg,
    wavecolor: wavecolors.native[0],
    progresscolor: wavecolors.native[1],
    top: '35%',
    left: '2%',   
    trackName: 'Yaqui Dance',
    trackMP3: 'songs/Yaqui-dance.mp3',
    trackStr: 'The music of the Yaquis has retained some original Indian aspects while adopting some Spanish factors; but this hybrid has become integrated through having been picked up by ear over a period of several hundered years.',
    'trackImg': 'music-of-the-worlds-people-iv.jpg',
    'trackArtist': '',
    'trackAlbum': 'Music of the World\'s People IV',
    'trackURL': 'https://folkways.si.edu/music-of-the-worlds-peoples-vol-4/islamica-world/album/smithsonian',
    locations: 'Sonora',
    'influences': 'Spanish',
    'instruments': 'Harp | Rattle'
  },
  {
    id: 'indigenous-06',
    genre: 'native',
    genresvg: nativesvg,
    wavecolor: wavecolors.native[0],
    progresscolor: wavecolors.native[1],
    top: '58%',
    left: '9%',  
    trackName: 'Danza del Arco, Toreado',
    trackMP3: 'songs/Danza-del-Arco-Toreado.mp3',
    trackStr: 'The violins now used by the Tarahumar Indians in Chihuahua are nearly perfect replicas oí their European prototypes oí the sixteenth century.',
    'trackImg': 'tarascan.jpg',
    'trackArtist': '',
    'trackAlbum': 'Tarascan and Other Music of Mexico',
    'trackURL': 'https://folkways.si.edu/tarascan-and-other-music-of-mexico-songs-and-dances-of-the-mexican-plateau/latin-world/album/smithsonian',
    locations: 'chihuahua',
    'influences': '',
    'instruments': 'Fiddles | Rattles'
  },
  {
    id: 'indigenous-07',
    genre: 'native',
    genresvg: nativesvg,
    wavecolor: wavecolors.native[0],
    progresscolor: wavecolors.native[1],
    top: '37%',
    left: '31%',  
    trackName: 'Medley of Tarahumara Indian Songs',
    trackMP3: 'songs/Medley-of-Tarahumara-Indian-Songs.mp3',
    trackStr: 'This is a medley of songs sung by the Tarahumares throughout the Sierra of southwestern Chihuahua',
    'trackImg': 'tarascan.jpg',
    'trackArtist': 'Ernestine Gaspar',
    'trackAlbum': 'Tarascan and Other Music of Mexico',
    'trackURL': 'https://folkways.si.edu/tarascan-and-other-music-of-mexico-songs-and-dances-of-the-mexican-plateau/latin-world/album/smithsonian',
    locations: 'chihuahua',
    'influences': '',
    'instruments': ''
  },
  {
    id: 'indigenous-08',
    genre: 'native',
    genresvg: nativesvg,
    wavecolor: wavecolors.native[0],
    progresscolor: wavecolors.native[1],
    top: '29%',
    left: '83%',   
    trackName: 'Ocarine, Transverse, Three Orifices...(Maya)',
    trackMP3: 'songs/Transverse-Flute.mp3',
    trackStr: 'This diversity which existed in the case of flutes existed also in the cases of whistle jars, trurapets of clay, sea shell instruments, gongs, drums, rasps, rattles etc .',
    'trackImg': 'pre-columbia.jpg',
    'trackArtist': '',
    'trackAlbum': 'Pre-Columbian Instruments',
    'trackURL': 'https://folkways.si.edu/jorje-daher/pre-columbian-instruments-of-mexico/american-indian-music-instruction-world/album/smithsonian',
    locations: 'yucatan',
    'influences': '',
    'instruments': 'Flute'
  },
  // {
  //   id: "corridos-01",
  //   trackName: "La Llorona (The Weeping Woman)",
  //   trackMP3: "songs/la-llorona.mp3",
  //   trackStr: "La Llorona is a mythical figure of Mexican folklore who comes out at night, clad in white, sobbing and shrieking as she looks for her children. As anyone who looks at her dies, her appearance is considered to be a bad omen.",
  //   "trackImg": "from-the-sky-of-my-childhood.jpg",
  //   "trackArtist": "Suni Paz",
  //   "trackAlbum": "From the Sky of My Childhood",
  //   "trackURL": "https://folkways.si.edu/suni-paz/from-the-sky-of-my-childhood/latin-world/music/album/smithsonian",
  //   genre: 'corridos',
  //   genresvg: corridossvg,
  //   wavecolor: wavecolors.corridos[0],
  //   progresscolor: wavecolors.corridos[1],
  //   top: 280,
  //   left: 1000,
  //   epicX: 830,
  //   epicY: 400,
  //   rotate: 20,
  //   "locations": "Azteca | Isthmus of Tehuantepec",
  //   "influences": "",
  //   "instruments": "Guitar | Cantante(s)"
  // },
  // {
  //   id: "corridos-02",
  //   trackName: "Corrido de Cananea",
  //   trackMP3: "corrido-de-cananea.mp3",
  //   trackStr: "Gather round, I'll tell you my story. By the leaves of an avocado And it's all about the capture of this reckless desperado. *liberities for rhyming",
  //   "trackImg": "corridos.jpg",
  //   "trackArtist": "Henry Cowell",
  //   "trackAlbum": "Corridos",
  //   "trackURL": "https://folkways.si.edu/mexican-corridos/latin-world/music/album/smithsonian",
  //   genre: 'corridos',
  //   genresvg: corridossvg,
  //   wavecolor: wavecolors.corridos[0],
  //   progresscolor: wavecolors.corridos[1],
  //   top: 280,
  //   left: 1000,
  //   epicX: 830,
  //   epicY: 400,
  //   rotate: 20,
  //   "locations": "",
  //   "influences": "Spanish",
  //   "instruments": "Guitar | Cantante(s)"
  // },
  // {
  //   id: "corridos-03",
  //   trackName: "El Arreglo Religioso",
  //   trackMP3: "el-arreglo-religioso.mp3",
  //   trackStr: "This is the story, gentlemen, /n of the religious troubles./nAnd how before things improved /n many sad days went by. /n Those were difficult times /n in which religion was banned.",
  //   "trackImg": "corridos.jpg",
  //   "trackArtist": "Henry Cowell",
  //   "trackAlbum": "Corridos",
  //   "trackURL": "https://folkways.si.edu/mexican-corridos/latin-world/music/album/smithsonian",
  //   genre: 'corridos',
  //   genresvg: corridossvg,
  //   wavecolor: wavecolors.corridos[0],
  //   progresscolor: wavecolors.corridos[1],
  //   top: 280,
  //   left: 1000,
  //   epicX: 830,
  //   epicY: 400,
  //   rotate: 20,
  //   "locations": "",
  //   "influences": "Spanish",
  //   "instruments": "Guitar | Cantante(s)"
  // },
  // {
  //   id: "corridos-04",
  //   trackName: "Prietita de Ojos Negros",
  //   trackMP3: "prietita-de-ojos-negras.mp3",
  //   trackStr: "Ah, my dark beauty with deep black eyes! /n Don't go telling anyone /n That around here folks are saying /n That I have you in my power",
  //   "trackImg": "corridos.jpg",
  //   "trackArtist": "Henry Cowell",
  //   "trackAlbum": "Corridos",
  //   "trackURL": "https://folkways.si.edu/mexican-corridos/latin-world/music/album/smithsonian",
  //   genre: 'corridos',
  //   genresvg: corridossvg,
  //   wavecolor: wavecolors.corridos[0],
  //   progresscolor: wavecolors.corridos[1],
  //   top: 280,
  //   left: 1000,
  //   epicX: 830,
  //   epicY: 400,
  //   rotate: 20,
  //   "locations": "",
  //   "influences": "Spanish",
  //   "instruments": "Guitar | Cantante(s)"
  // },
  // {
  //   id: "corridos-05",
  //   trackName: "Toma de Gelava",
  //   trackMP3: "toma-de-gelava.mp3",
  //   trackStr: "In April, the first of the month /n On Holy Thursday in the morning, /n Villa went forth from Parral /n To launch and speed up a campaign",
  //   "trackImg": "corridos.jpg",
  //   "trackArtist": "Henry Cowell",
  //   "trackAlbum": "Corridos",
  //   "trackURL": "https://folkways.si.edu/mexican-corridos/latin-world/music/album/smithsonian",
  //   genre: 'corridos',
  //   genresvg: corridossvg,
  //   wavecolor: wavecolors.corridos[0],
  //   progresscolor: wavecolors.corridos[1],
  //   top: 280,
  //   left: 1000,
  //   epicX: 830,
  //   epicY: 400,
  //   rotate: 20,
  //   "locations": "",
  //   "influences": "Spanish",
  //   "instruments": "Guitar | Cantante(s)"
  // },
  // {
  //   id: "corridos-06",
  //   trackName: "Jesús Leal",
  //   trackMP3: "Jesus-Leal.mp3",
  //   trackStr: "On the 28th of january, I wish I could forget, Don Felix Alba came to arrest jesus Leal.",
  //   "trackImg": "mex-revolution.jpg",
  //   "trackArtist": "",
  //   "trackAlbum": "The Mexican Revolution Corridos",
  //   "trackURL": "https://folkways.si.edu/mexican-revolution-corridos-heroes-and-events-1910-1920-and-beyond-cd/latin-world/music/album/smithsonian",
  //   genre: 'corridos',
  //   genresvg: corridossvg,
  //   wavecolor: wavecolors.corridos[0],
  //   progresscolor: wavecolors.corridos[1],
  //   top: 280,
  //   left: 1000,
  //   epicX: 830,
  //   epicY: 400,
  //   rotate: 20,
  //   "locations": "",
  //   "influences": "",
  //   "instruments": "Guitar | Cantante(s)"
  // },
  // {
  //   id: "corridos-07",
  //   trackName: "Adelita",
  //   trackMP3: "Adelita.mp3",
  //   trackStr: "Adelita is the name of the ungrateful one,  the one who owned my love.  Don't ever think that I would forget her or exchange her for another woman.",
  //   "trackImg": "mex-revolution.jpg",
  //   "trackArtist": "",
  //   "trackAlbum": "The Mexican Revolution Corridos",
  //   "trackURL": "https://folkways.si.edu/mexican-revolution-corridos-heroes-and-events-1910-1920-and-beyond-cd/latin-world/music/album/smithsonian",
  //   genre: 'corridos',
  //   genresvg: corridossvg,
  //   wavecolor: wavecolors.corridos[0],
  //   progresscolor: wavecolors.corridos[1],
  //   top: 280,
  //   left: 1000,
  //   epicX: 830,
  //   epicY: 400,
  //   rotate: 20,
  //   "locations": "",
  //   "influences": "",
  //   "instruments": "guitar | Cantante(s)"
  // },
  // {
  //   id: "corridos-08",
  //   trackName: "México-Americano",
  //   trackMP3: "Mexico-Americano.mp3",
  //   trackStr: "The song \"Mexico-Americano\" urges Mexican-Americans to see the strengths of being bilingual and bicultural, and to appreciate their rich heritage.",
  //   "trackImg": "corridos-chicano.jpg",
  //   "trackArtist": "",
  //   "trackAlbum": "Corridos of the Chicano Movement",
  //   "trackURL": "https://folkways.si.edu/rumel-fuentes/corridos-of-the-chicano-movement/latin-world/music/album/smithsonian",
  //   genre: 'corridos',
  //   genresvg: corridossvg,
  //   wavecolor: wavecolors.corridos[0],
  //   progresscolor: wavecolors.corridos[1],
  //   top: 280,
  //   left: 1000,
  //   epicX: 830,
  //   epicY: 400,
  //   rotate: 20,
  //   "locations": "Texas",
  //   "influences": "",
  //   "instruments": "guitar | Cantante(s)"
  // },
  // {
  //   id: "corridos-09",
  //   trackName: "Voy a Cantar un Corrido",
  //   trackMP3: "Voy-a-Cantar-un-Corrido.mp3",
  //   trackStr: "I will sing a corrido, Of a friend from my village, Whose name was Valentin and who was shot and judged.",
  //   "trackImg": "traditional-songs-of-mexico.jpg",
  //   "trackArtist": "",
  //   "trackAlbum": "Traditional Songs of Mexico",
  //   "trackURL": "https://folkways.si.edu/carlos-jaso-ruben-lopez-mario-quiroz-and-oscar-chavez/traditional-songs-of-mexico/latin-world/music/album/smithsonian",
  //   genre: 'corridos',
  //   genresvg: corridossvg,
  //   wavecolor: wavecolors.corridos[0],
  //   progresscolor: wavecolors.corridos[1],
  //   top: 280,
  //   left: 1000,
  //   epicX: 830,
  //   epicY: 400,
  //   rotate: 20,
  //   "locations": "",
  //   "influences": "Spanish",
  //   "instruments": "Guitar | Cantante(s)"
  // },
  // {
  //   id: "corridos-10",
  //   trackName: "El Deportado",
  //   trackMP3: "El-Deportado.mp3",
  //   trackStr: "I'm going to tell you, gentlemen, (2X) all about my sufferings. Since I left my country, (2X) to come to this nation.",
  //   "trackImg": "corridos-tragedias.jpg",
  //   "trackArtist": "Los Hermoanos Banuelos",
  //   "trackAlbum": "Corridos & Tragedias de la Frontera",
  //   "trackURL": "https://folkways.si.edu/corridos-tragedias-de-la-frontera-mexican-american-ballads-1928-1937/latin-world/music/album/smithsonian",
  //   genre: 'corridos',
  //   genresvg: corridossvg,
  //   wavecolor: wavecolors.corridos[0],
  //   progresscolor: wavecolors.corridos[1],
  //   top: 280,
  //   left: 1000,
  //   epicX: 830,
  //   epicY: 400,
  //   rotate: 20,
  //   "locations": "Northern Mexico",
  //   "influences": "Spanish",
  //   "instruments": "Guitar | Cantante(s)"
  // },
  // {
  //   id: "mariachi-01",
  //   trackName: "La Malagueña",
  //   trackMP3: "La-Malaguena.mp3",
  //   trackStr: "Sung in the falsetto style typical of some Mexican songs, this exciting song says \"what beautiful eyes you have . . . how I wish they would look at me . . . Even though I am poor I offer you all my love.",
  //   "trackImg": "mariachi-sound.jpg",
  //   "trackArtist": "William Clauson",
  //   "trackAlbum": "The Mariachi Sound",
  //   "trackURL": "https://folkways.si.edu/william-clauson-and-the-oro-y-plata-de-pepe-chavez-mariachi-ensemble/the-mariachi-sound/latin-world/music/album/smithsonian",
  //   "genre": "Mariachi",
  //   "locations": "",
  //   "influences": "French | Spanish",
  //   "instruments": "Violins | Guitars | Trumpets"
  // },
  // {
  //   id: "mariachi-02",
  //   trackName: "From Monterrey",
  //   trackMP3: "from-monterrey.mp3",
  //   trackStr: "Full-blown type performance born of fierce big-city competition between bands",
  //   "trackImg": "mariachi-music-of-mexico.jpg",
  //   "trackArtist": "Sam Eskin",
  //   "trackAlbum": "Mariachi Music of Mexico",
  //   "trackURL": "https://folkways.si.edu/mariachi-music-of-mexico/latin-world/music/album/smithsonian",
  //   "genre": "Mariachi",
  //   "locations": "Monterrey",
  //   "influences": "French | Spanish",
  //   "instruments": "violins | vihuela | 6-string guitar | guitarron | trumpet"
  // },
  // {
  //   id: "mariachi-03",
  //   trackName: "Ay, Jalisco No Te Rajes!",
  //   trackMP3: "ay-jalisco.mp3",
  //   trackStr: "Jalisco, don't back down, \" the tille of this song has long been a rallying cry for all Tapatios.",
  //   "trackImg": "mariachi-jalisco.jpg",
  //   "trackArtist": "",
  //   "trackAlbum": "Mariachi Aguilas de Chapala",
  //   "trackURL": "https://folkways.si.edu/mariachi-aguilas-de-chapala/latin-world/music/album/smithsonian",
  //   "genre": "Mariachi",
  //   "locations": "Jalisco",
  //   "influences": "French | Spanish",
  //   "instruments": "Violin | Guitar | Guitarron | Vihuela"
  // },
  // {
  //   id: "norteno-01",
  //   trackName: "Polka",
  //   trackMP3: "polka.jpg",
  //   trackStr: "The Polka is one of a very large number of dance forms in Nortena music influenced European migrant culture.",
  //   "trackImg": "spanish-mexican-folk-music.jpg",
  //   "trackArtist": "",
  //   "trackAlbum": "Spanish and Mexican Folk Music of New Mexico",
  //   "trackURL": "https://folkways.si.edu/spanish-and-mexican-folk-music-of-new-mexico/american-folk-latin/album/smithsonian",
  //   "genre": "Norteno",
  //   "locations": "Northern Mexico, Lower USA",
  //   "influences": "German",
  //   "instruments": "Violin | Guitar | Accordion | Trumpet"
  // },
  // {
  //   id: "norteno-02",
  //   trackName: "Grasshopper Waltz",
  //   trackMP3: "grasshopper-waltz.mp3",
  //   trackStr: "Although the composer calls it a waltz, it is too fast to be danced to and is not even in the usual waltz time.",
  //   "trackImg": "spanish-mexican-folk-music.jpg",
  //   "trackArtist": "",
  //   "trackAlbum": "Spanish and Mexican Folk Music of New Mexico",
  //   "trackURL": "https://folkways.si.edu/spanish-and-mexican-folk-music-of-new-mexico/american-folk-latin/album/smithsonian",
  //   "genre": "Norteno",
  //   "locations": "Northern Mexico, Lower USA",
  //   "influences": "German",
  //   "instruments": "Guitar"
  // },
  // {
  //   id: "norteno-03",
  //   trackName: "Cancion Ingles",
  //   trackMP3: "cancion-ingles.mp3",
  //   trackStr: "Since I came to this place I have begun to learn English And I am already so advanced That I have learned to say \"yes",
  //   "trackImg": "spanish-mexican-folk-music.jpg",
  //   "trackArtist": "",
  //   "trackAlbum": "Spanish and Mexican Folk Music of New Mexico",
  //   "trackURL": "https://folkways.si.edu/spanish-and-mexican-folk-music-of-new-mexico/american-folk-latin/album/smithsonian",
  //   "genre": "Norteno",
  //   "locations": "Northern Mexico, Lower USA",
  //   "influences": "German",
  //   "instruments": "Guitar"
  // },
  // {
  //   id: "norteno-04",
  //   trackName: "Patricia",
  //   trackMP3: "patricia.mp3",
  //   trackStr: "The unique accordion music of south Texas and northern Mexico (known as nortefzo on the Mexican side and simply as conjunto on the US side) was little known and even less recognized outside its home turf. Since then, however, this danceable, joyful, lilting music from the vast and isolated border region has developed into perhaps the most widely known of all Mexican regional sryles.",
  //   "trackImg": "accordion.jpg",
  //   "trackArtist": "Pedro Ayala",
  //   "trackAlbum": "Accordion Conjunto Champs",
  //   "trackURL": "https://folkways.si.edu/accordion-conjunto-champs/latin-world/music/album/smithsonian",
  //   "genre": "Norteno",
  //   "locations": "Northern Mexico, Lower USA",
  //   "influences": "German | French",
  //   "instruments": "Accordion | Guitar"
  // },
  // {
  //   id: "norteno-05",
  //   trackName: "Yo Me Enamore",
  //   trackMP3: "Yo-Me-Enamore.mp3",
  //   trackStr: "I fell in love with a woman thinking that she loved me; I was disillusioned by her ways. And she mocked my love.",
  //   "trackImg": "tex-mex-conjuntos.jpg",
  //   "trackArtist": "Fred Zimmerle’s Trio San Antonio",
  //   "trackAlbum": "Conjuntos Norteños",
  //   "trackURL": "https://folkways.si.edu/los-pinguinos-fred-zimmerles-trio-san-antonio/conjuntos-nortenos/latin-world/music/album/smithsonian",
  //   "genre": "Norteno",
  //   "locations": "Northern Mexico, Lower USA",
  //   "influences": "German | French",
  //   "instruments": "accordion | bajo sexto | bass | drums"
  // },
  // {
  //   id: "norteno-06",
  //   trackName: "Yo Soy Norteño",
  //   trackMP3: "yo-soy-norteno.mp3",
  //   trackStr: "I'm a northerner from the real north. I'm master of my sorrow; Now my passport is ready. Now I feel free in my heart.",
  //   "trackImg": "tex-mex-conjuntos.jpg",
  //   "trackArtist": "Fred Zimmerle’s Trio San Antonio",
  //   "trackAlbum": "Conjuntos Norteños",
  //   "trackURL": "https://folkways.si.edu/los-pinguinos-fred-zimmerles-trio-san-antonio/conjuntos-nortenos/latin-world/music/album/smithsonian",
  //   "genre": "Norteno",
  //   "locations": "Northern Mexico, Lower USA",
  //   "influences": "German | French",
  //   "instruments": "accordion | bajo sexto | bass | drums"
  // },
  // {
  //   id: "rancheras-01",
  //   trackName: "Estoy como el Gallo Giro",
  //   trackMP3: "Estoy-como-el-Gallo-Giro.mp3",
  //   trackStr: "I am like a yellowish rooster from the market fence, asking the poultrymen to give me to anyone.",
  //   "trackImg": "traditional-songs-of-mexico.jpg",
  //   "trackArtist": "",
  //   "trackAlbum": "Traditional Songs of Mexico",
  //   "trackURL": "https://folkways.si.edu/carlos-jaso-ruben-lopez-mario-quiroz-and-oscar-chavez/traditional-songs-of-mexico/latin-world/music/album/smithsonian",
  //   "genre": "Rancheras",
  //   "locations": "",
  //   "influences": "Spanish",
  //   "instruments": "Guitar | Cantante(s)"
  // },
  // {
  //   id: "rancheras-02",
  //   trackName: "Entre Cerros y Montañas",
  //   trackMP3: "Entre-Cerros-y-Montañas.mp3",
  //   trackStr: "Between hills and mountains is the village where I was born. The memories of mornings I lived through.",
  //   "trackImg": "traditional-songs-of-mexico.jpg",
  //   "trackArtist": "",
  //   "trackAlbum": "Traditional Songs of Mexico",
  //   "trackURL": "https://folkways.si.edu/carlos-jaso-ruben-lopez-mario-quiroz-and-oscar-chavez/traditional-songs-of-mexico/latin-world/music/album/smithsonian",
  //   "genre": "Rancheras",
  //   "locations": "",
  //   "influences": "Spanish",
  //   "instruments": "Guitar | Cantante(s)"
  // },
  // {
  //   id: "rancheras-03",
  //   trackName: "Yo ya me Voy ya me Voy",
  //   trackMP3: "Yo-ya-me-Voy-ya-me-Voy.mp3",
  //   trackStr: "Now I will go away, now I will go, because I don't belong here. My loves are far away from here, they are very far away.",
  //   "trackImg": "traditional-songs-of-mexico.jpg",
  //   "trackArtist": "",
  //   "trackAlbum": "Traditional Songs of Mexico",
  //   "trackURL": "https://folkways.si.edu/carlos-jaso-ruben-lopez-mario-quiroz-and-oscar-chavez/traditional-songs-of-mexico/latin-world/music/album/smithsonian",
  //   "genre": "Rancheras",
  //   "locations": "",
  //   "influences": "Spanish",
  //   "instruments": "Guitar | Cantante(s)"
  // },
  // {
  //   id: "rancheras-04",
  //   trackName: "El Toro Bravo (The Wild Bull)",
  //   trackMP3: "el-toro-bravo.mp3",
  //   trackStr: "There goes the foreman So drunk he is staggering. There goes the foreman So drunk he is staggering.",
  //   "trackImg": "peter-hurd.jpg",
  //   "trackArtist": "Peter Hurd",
  //   "trackAlbum": "Spanish Folk Songs of New Mexico",
  //   "trackURL": "https://folkways.si.edu/peter-hurd/spanish-folk-songs-of-new-mexico/american-folk-latin/music/album/smithsonian",
  //   "genre": "Rancheras",
  //   "locations": "",
  //   "influences": "Spanish",
  //   "instruments": "Guitar | Cantante(s)"
  // },
  // {
  //   id: "rancheras-05",
  //   trackName: "El Palo Verde (The Palo Verde Tree)",
  //   trackMP3: "El-Palo-Verde.mp3",
  //   trackStr: "Lady, your paloverde tree was drying; up on you Until last nieht I watered. it and Today by dawn it was in bloom.",
  //   "trackImg": "peter-hurd.jpg",
  //   "trackArtist": "Peter Hurd",
  //   "trackAlbum": "Spanish Folk Songs of New Mexico",
  //   "trackURL": "https://folkways.si.edu/peter-hurd/spanish-folk-songs-of-new-mexico/american-folk-latin/music/album/smithsonian",
  //   "genre": "Rancheras",
  //   "locations": "",
  //   "influences": "Spanish",
  //   "instruments": "Guitar | Cantante(s)"
  // },
  // {
  //   id: "rancheras-06",
  //   trackName: "El Sombrerito (The Little Hat)",
  //   trackMP3: "El-Sombrerito.mp3",
  //   trackStr: "This hat I am wearing I have brouBht from Chicon. I have brought from Chicon -. ay, This hat I am wearing",
  //   "trackImg": "peter-hurd.jpg",
  //   "trackArtist": "Peter Hurd",
  //   "trackAlbum": "Spanish Folk Songs of New Mexico",
  //   "trackURL": "https://folkways.si.edu/peter-hurd/spanish-folk-songs-of-new-mexico/american-folk-latin/music/album/smithsonian",
  //   "genre": "Rancheras",
  //   "locations": "",
  //   "influences": "Spanish",
  //   "instruments": "Guitar | Cantante(s)"
  // },
  // {
  //   id: "rancheras-07",
  //   trackName: "Las Chaparreras",
  //   trackMP3: "Las-Chaparreras.mp3",
  //   trackStr: "When! came to the city I bought myself some chapar~eras And then I returned tb the ranCh To make love to the ranch girls.",
  //   "trackImg": "peter-hurd.jpg",
  //   "trackArtist": "Peter Hurd",
  //   "trackAlbum": "Spanish Folk Songs of New Mexico",
  //   "trackURL": "https://folkways.si.edu/peter-hurd/spanish-folk-songs-of-new-mexico/american-folk-latin/music/album/smithsonian",
  //   "genre": "Rancheras",
  //   "locations": "",
  //   "influences": "Spanish",
  //   "instruments": "Guitar | Cantante(s)"
  // },
  // {
  //   id: "rancheras-08",
  //   trackName: "La Cariñosa (Be Kind to Me)",
  //   trackMP3: "La-Carinosa.mp3",
  //   trackStr: "Sorrow oppresses my heart, and you my love are the cause, for being so sweet",
  //   "trackImg": "songs-of-mexico.jpg",
  //   "trackArtist": "Timothy Harding",
  //   "trackAlbum": "Songs of Mexico",
  //   "trackURL": "https://folkways.si.edu/songs-of-mexico/latin-world/music/album/smithsonian",
  //   "genre": "Rancheras",
  //   "locations": "",
  //   "influences": "Spanish",
  //   "instruments": "Guitar | Cantante(s)"
  // },
  // {
  //   id: "rancheras-09",
  //   trackName: "Tzutzuquetzutzúmacua",
  //   trackMP3: "Tzutzuquetzutzumacua.mp3",
  //   trackStr: "",
  //   "trackImg": "tarascan.jpg",
  //   "trackArtist": "",
  //   "trackAlbum": "Tarascan and Other Music of Mexico",
  //   "trackURL": "https://folkways.si.edu/tarascan-and-other-music-of-mexico-songs-and-dances-of-the-mexican-plateau/latin-world/album/smithsonian",
  //   "genre": "Rancheras",
  //   "locations": "Mexican Plateau",
  //   "influences": "",
  //   "instruments": "Guitar | Cantante(s)"
  // },
  // {
  //   id: "rancheras-10",
  //   trackName: "La Malagueña Guerrerense",
  //   trackMP3: "La-Malaguena-Guerrerense.mp3",
  //   trackStr: "What to do I fly away What to do I fly away Well I like joy With shame I'm singing",
  //   "trackImg": "Sones-of-Mexico.jpg",
  //   "trackArtist": "Trio Aguilillas",
  //   "trackAlbum": "Sones of Mexico",
  //   "trackURL": "https://folkways.si.edu/trio-aguilillas/sones-of-mexico/latin-world/music/album/smithsonian",
  //   "genre": "Rancheras",
  //   "locations": "Guerrero",
  //   "influences": "Spanish",
  //   "instruments": "Spanish Guitar | Cantante(s)"
  // },
  // {
  //   id: "son-huestecos-01",
  //   trackName: "Balajú",
  //   trackMP3: "Balaju.mp3",
  //   trackStr: "Balaju went off to the wars, hey; And he wouldn't take me along. And he wouldn't take me along - Baleju went off to the wars.",
  //   "trackImg": "songs-of-mexico.jpg",
  //   "trackArtist": "Timothy Harding",
  //   "trackAlbum": "Songs of Mexico",
  //   "trackURL": "https://folkways.si.edu/songs-of-mexico/latin-world/music/album/smithsonian",
  //   "genre": "Son Huestecos/Huapangos",
  //   "locations": "Las Huastecas |.Tamaulipas",
  //   "influences": "",
  //   "instruments": "Violin | Guitarra huapanguera | Jarana"
  // },
  // {
  //   id: "son-huestecos-02",
  //   trackName: "La Petenera",
  //   trackMP3: "La-Petenera.mp3",
  //   trackStr: "The mestiza music began to develop even a relatively short time after Cortés’s conquest of the land of Huitzilopochtli. Today, more than four centuries later, the Spanish roots can clearly be recognized in most of the songs and dances that do not preserve an outright Indian character...",
  //   "trackImg": "Sones-of-Mexico.jpg",
  //   "trackArtist": "",
  //   "trackAlbum": "Sones of Mexico",
  //   "trackURL": "https://folkways.si.edu/trio-aguilillas/sones-of-mexico/latin-world/music/album/smithsonian",
  //   "genre": "Son Huestecos/Huapangos",
  //   "locations": "Las Huastecas |.Tamaulipas",
  //   "influences": "",
  //   "instruments": "Violin | Guitarra huapanguera | Jarana"
  // },
  // {
  //   id: "son-huestecos-03",
  //   trackName: "Huapango Los Trabajos",
  //   trackMP3: "Huapango-Los-Trabajos.mp3",
  //   trackStr: "Whole families rose at dawn, drove to the fields, and worked in backbreaking labor until dusk. In spring there would still be frost on the ground, and in summer temperatures could reach 1 00 degrees.",
  //   "trackImg": "corridos-chicano.jpg",
  //   "trackArtist": "",
  //   "trackAlbum": "Corridos of the Chicano Movement",
  //   "trackURL": "https://folkways.si.edu/rumel-fuentes/corridos-of-the-chicano-movement/latin-world/music/album/smithsonian",
  //   "genre": "Son Huestecos/Huapangos",
  //   "locations": "Las Huastecas |.Tamaulipas",
  //   "influences": "",
  //   "instruments": "Violin | Guitarra huapanguera | Jarana"
  // },
  // {
  //   id: "son-huestecos-04",
  //   trackName: "La Llorona",
  //   trackMP3: "la-llorona-2.mp3",
  //   trackStr: "They tell me not to cry for her that she left because she wanted to and I tell you folks that crying is an urgent thing",
  //   "trackImg": "huapangos.jpg",
  //   "trackArtist": "",
  //   "trackAlbum": "Huapangos y Sones Huastecos",
  //   "trackURL": "https://folkways.si.edu/los-caimanes-los-caporales-de-panuco/huapangos-y-sones-huastecos/latin/music/album/smithsonian",
  //   "genre": "Son Huestecos/Huapangos",
  //   "locations": "Las Huastecas |.Tamaulipas",
  //   "influences": "",
  //   "instruments": "Violin | Guitarra huapanguera | Jarana"
  // },
  // {
  //   id: "son-huestecos-05",
  //   trackName: "El Caballito",
  //   trackMP3: "el-caballito.mp3",
  //   trackStr: "I'm going out to hunt all the way to San Luis Potosi (2X) I'm going out to hunt",
  //   "trackImg": "huapangos.jpg",
  //   "trackArtist": "",
  //   "trackAlbum": "Huapangos y Sones Huastecos",
  //   "trackURL": "https://folkways.si.edu/los-caimanes-los-caporales-de-panuco/huapangos-y-sones-huastecos/latin/music/album/smithsonian",
  //   "genre": "Son Huestecos/Huapangos",
  //   "locations": "Las Huastecas |.Tamaulipas",
  //   "influences": "",
  //   "instruments": "Violin | Guitarra huapanguera | Jarana"
  // },
  // {
  //   id: "son-huestecos-06",
  //   trackName: "La Gata",
  //   trackMP3: "la-gata.mp3",
  //   trackStr: "How nice it is to work In the boss's house But I lost the job Because of the mischievous cat",
  //   "trackImg": "huapangos.jpg",
  //   "trackArtist": "",
  //   "trackAlbum": "Huapangos y Sones Huastecos",
  //   "trackURL": "https://folkways.si.edu/los-caimanes-los-caporales-de-panuco/huapangos-y-sones-huastecos/latin/music/album/smithsonian",
  //   "genre": "Son Huestecos/Huapangos",
  //   "locations": "Las Huastecas |.Tamaulipas",
  //   "influences": "",
  //   "instruments": "Violin | Guitarra huapanguera | Jarana"
  // },
  // {
  //   id: "son-huestecos-07",
  //   trackName: "El Relampago",
  //   trackMP3: "El-Relampago.mp3",
  //   trackStr: "The translated title of this piece means lightening bolt and that describes the quick, driving rhythm that propels this piece.",
  //   "trackImg": "border-bash.jpg",
  //   "trackArtist": "",
  //   "trackAlbum": "Border Bash: Tex-Mex Dance Music, Vol. 2",
  //   "trackURL": "https://folkways.si.edu/los-polkeros-de-ben-tavera-king/border-bash-tex-mex-dance-music-vol-2/latin-world/album/smithsonian",
  //   "genre": "Son Huestecos/Huapangos",
  //   "locations": "Las Huastecas |.Tamaulipas | Northern Mexico",
  //   "influences": "German | Polish | African",
  //   "instruments": "Buttton Accordion | Bajo Sexto | Guitar"
  // },
  // {
  //   id: "son-jarocho-01",
  //   trackName: "La Bamba (The Bamba)",
  //   trackMP3: "la-bamba.mp3",
  //   trackStr: "If you want to dance the bamba, You must have feet that are nimble",
  //   "trackImg": "songs-of-mexico.jpg",
  //   "trackArtist": "Timothy Harding",
  //   "trackAlbum": "Songs of Mexico",
  //   "trackURL": "https://folkways.si.edu/songs-of-mexico/latin-world/music/album/smithsonian",
  //   "genre": "Son Jarocho",
  //   "locations": "Veracruz",
  //   "influences": "Spanish, African, Carribean",
  //   "instruments": "Jarana | Fiddles"
  // },
  // {
  //   id: "son-jarocho-02",
  //   trackName: "Pajarito (Little Bird)",
  //   trackMP3: "pajarito.mp3",
  //   trackStr: "Little bird, you're pretty, But even prettier you'd be If you did me a favor, And flew with this little note, To the lady of my heart.",
  //   "trackImg": "songs-of-mexico.jpg",
  //   "trackArtist": "Timothy Harding",
  //   "trackAlbum": "Songs of Mexico",
  //   "trackURL": "https://folkways.si.edu/songs-of-mexico/latin-world/music/album/smithsonian",
  //   "genre": "Son Jarocho",
  //   "locations": "Veracruz",
  //   "influences": "Spanish, African, Carribean",
  //   "instruments": "Jarana | Fiddles"
  // },
  // {
  //   id: "son-jarocho-03",
  //   trackName: "Song of the Pollitos",
  //   trackMP3: "Song-of-the-Pollitos.mp3",
  //   trackStr: "The Rio Blanco Singers play the original instruments of Veracruz: the harp, the jarana la small guitar), the requinto (a four-string guitar) and a regular Spanish guitar.",
  //   "trackImg": "fiesta-mexicana.jpg",
  //   "trackArtist": "Javier de Leon",
  //   "trackAlbum": "Fiesta Mexicana",
  //   "trackURL": "https://folkways.si.edu/javier-de-leon/fiesta-mexicana-panorama-of-mexico-old-and-new/latin-world/music/album/smithsonian",
  //   "genre": "Son Jarocho",
  //   "locations": "Veracruz",
  //   "influences": "Spanish, African, Carribean",
  //   "instruments": "Jarana | Harp | Requinto | Spanish Guitar"
  // },
  // {
  //   id: "son-jarocho-04",
  //   trackName: "La Cumbamba",
  //   trackMP3: "La-Cumbamba.mp3",
  //   trackStr: "The Rio Blanco Singers play the original instruments of Veracruz: the harp, the jarana la small guitar), the requinto (a four-string guitar) and a regular Spanish guitar. Sounds of the dancers in the background.",
  //   "trackImg": "fiesta-mexicana.jpg",
  //   "trackArtist": "Javier de Leon",
  //   "trackAlbum": "Fiesta Mexicana",
  //   "trackURL": "https://folkways.si.edu/javier-de-leon/fiesta-mexicana-panorama-of-mexico-old-and-new/latin-world/music/album/smithsonian",
  //   "genre": "Son Jarocho",
  //   "locations": "Veracruz",
  //   "influences": "Spanish, African, Carribean",
  //   "instruments": "Jarana | Harp | Requinto | Spanish Guitar"
  // },
  // {
  //   id: "son-jarocho-05",
  //   trackName: "El Pajaro Carpintero",
  //   trackMP3: "Song-of-El-Pajaro-Carpintero.mp3",
  //   trackStr: "The Rio Blanco Singers play the original instruments of Veracruz: the harp, the jarana la small guitar), the requinto (a four-string guitar) and a regular Spanish guitar. Sounds of the dancers in the background.",
  //   "trackImg": "fiesta-mexicana.jpg",
  //   "trackArtist": "Javier de Leon",
  //   "trackAlbum": "Fiesta Mexicana",
  //   "trackURL": "https://folkways.si.edu/javier-de-leon/fiesta-mexicana-panorama-of-mexico-old-and-new/latin-world/music/album/smithsonian",
  //   "genre": "Son Jarocho",
  //   "locations": "Veracruz",
  //   "influences": "Spanish, African, Carribean",
  //   "instruments": "Jarana | Harp | Requinto | Spanish Guitar"
  // },
  // {
  //   id: "son-jarocho-06",
  //   trackName: "El Coco",
  //   trackMP3: "el-coco.mp3",
  //   trackStr: "While mosl sones feature a lead singer in close alternation with one or more singers who respond by repeating or answering lhe leader's phrase, \"Coco\" is one of the l'ew that ineludes a short. repeated response, hinting at African origins. \"They say that coconut is good cooked in fine spices. but I say no. that chicken is better.",
  //   "trackImg": "la-bamba-sones-jarochos-from-veracruz.jpg",
  //   "trackArtist": "José Gutiérrez & Los Hermanos Ochoa",
  //   "trackAlbum": "La Bamba: Sones Jarochos from Veracruz",
  //   "trackURL": "https://folkways.si.edu/jose-gutierrez-los-hermanos-ochoa/la-bamba-sones-jarochos-from-veracruz/latin-world/music/album/smithsonian",
  //   "genre": "Son Jarocho",
  //   "locations": "Veracruz",
  //   "influences": "Spanish, African, Carribean",
  //   "instruments": "Jarana | Harp | Miramba | Drums"
  // },
  // {
  //   id: "son-jarocho-07",
  //   trackName: "El Cascabel",
  //   trackMP3: "El-Cascabel.mp3",
  //   trackStr: "The mestiza music began to develop even a relatively short time after Cortés’s conquest of the land of Huitzilopochtli. Today, more than four centuries later, the Spanish roots can clearly be recognized in most of the songs and dances that do not preserve an outright Indian character...",
  //   "trackImg": "Sones-of-Mexico.jpg",
  //   "trackArtist": "",
  //   "trackAlbum": "Sones of Mexico",
  //   "trackURL": "https://folkways.si.edu/trio-aguilillas/sones-of-mexico/latin-world/music/album/smithsonian",
  //   "genre": "Son Jarocho",
  //   "locations": "Veracruz",
  //   "influences": "Spanish, African, Carribean",
  //   "instruments": ""
  // },
  // {
  //   id: 'banda-01',
  //   genre: 'banda',
  //   genresvg: bandasvg,
  //   wavecolor: wavecolors.banda[0],
  //   progresscolor: wavecolors.banda[1],
  //   top: 280,
  //   left: 1000,
  //   epicX: 430,
  //   epicY: 100,
  //   rotate: 0,
  //   trackName: 'Marcha Zacatecas',
  //   trackImg: '',
  //   trackMP3: 'songs/./songs/Marcha-Zacatecas.mp3',
  //   trackStr: `Alludes to the military genre, but soon turns 
  //              into a highly danceable tune. As often with 
  //              marches, a lyric trio alternates with the 
  //              march proper. The genre was much in vogue 
  //              among rural audiences, and local banderos 
  //              continued to compose marches well into the 
  //              twentieth century`
  // },
  // // {
  // //   id: "banda-01",
  // //   trackName: "Marcha Zacatecas",
  // //   trackMP3: "Marcha-Zacatecas.mp3",
  // //   trackStr: "Alludes to the military genre, but soon turns into a highly danceable tune. As often with marches, a lyric trio alternates with the march proper. The genre was much in vogue among rural audiences, and local banderos continued to compose marches well into the twentieth century",
  // //   epicX: rand(0, 1100),
  // //   epicY: rand(0, 500),
  // //   "trackImg": "bandas.jpg",
  // //   "trackArtist": "Banda de Mocorito de Nilo Gallardo",
  // //   "trackAlbum": "Bandas Sinaloenses Música Tambora",
  // //   "trackURL": "https://folkways.si.edu/bandas-sinaloenses-musica-tambora/latin-world/music/album/smithsonian",
  // // genre: 'banda',
  //   // genresvg: bandasvg,
  //   // epicX: rand(0, 1100),
  //   // epicY: rand(0, 500),
  // //   "locations": "Zacatecas",
  // //   "influences": "German | Polish",
  // //   "instruments": "Trombone | Tuba | Trumpets | Horns | Drums"
  // // },
  // {
  //   id: "banda-02",
  //   trackName: "La India Bonita",
  //   trackMP3: "La-India-Bonita.mp3",
  //   trackStr: "Valse composed by Francisco Terrfquez from the village of La Noria, have become banda standards",
  //   "trackImg": "bandas.jpg",
  //   "trackArtist": "Banda Típica de Mazatlán",
  //   "trackAlbum": "Bandas Sinaloenses Música Tambora",
  //   "trackURL": "https://folkways.si.edu/bandas-sinaloenses-musica-tambora/latin-world/music/album/smithsonian",
  //   genre: 'banda',
  //   genresvg: bandasvg,
  //   wavecolor: wavecolors.banda[0],
  //   progresscolor: wavecolors.banda[1],
  //   top: 280,
  //   left: 1000,
  //   epicX: 530,
  //   epicY: 400,
  //   rotate: 40,
  //   "locations": "Sinaloa",
  //   "influences": "German | Polish",
  //   "instruments": "Clarinets | Trombone | Tuba | Trumpets | Horns | Drums"
  // },
  // {
  //   id: "banda-03",
  //   trackName: "El Guango",
  //   trackMP3: "El-Guango.mp3",
  //   trackStr: "El guango\", for example, maybe used to ridicule a rival's manliness in public",
  //   "trackImg": "bandas.jpg",
  //   "trackArtist": "Banda Los Guamuchileños de Culiacán",
  //   "trackAlbum": "Bandas Sinaloenses Música Tambora",
  //   "trackURL": "https://folkways.si.edu/bandas-sinaloenses-musica-tambora/latin-world/music/album/smithsonian",
  //   genre: 'banda',
  //   genresvg: bandasvg,
  //   wavecolor: wavecolors.banda[0],
  //   progresscolor: wavecolors.banda[1],
  //   top: 280,
  //   left: 1000,
  //   epicX: 830,
  //   epicY: 400,
  //   rotate: 20,
  //   "locations": "Sinaloa",
  //   "influences": "Polish",
  //   "instruments": "Clarinets | Trombone | Tuba | Trumpets | Horns | Drums"
  // }
];

export { data };